apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: dev-tools
data:
  jvm.options: |
    -Xms2g -Xmx4g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -Djava.awt.headless=true

