apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30007
    - name: jnlp
      port: 50000
      targetPort: 50000
      nodePort: 30008

