apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      initContainers:
      - name: init-jenkins
        image: busybox
        command:
        - sh
        - -c
        - >
          echo "Setting JVM options...";
          mkdir -p /var/jenkins_home;
          echo '-Xms2g -Xmx4g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -Djava.awt.headless=true' > /var/jenkins_home/jvm.options;
      containers:
      - name: jenkins-app
        image: jenkins/jenkins:lts
        ports:
        - name: httpport
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000
        env:
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: jenkins-config
              key: jvm.options
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: jenkins-storage
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-storage
        persistentVolumeClaim:
          claimName: jenkins-pvc

